### ISSUE TITLE
Tproxy support for listen directive

### ISSUE THREAD

**Issue by rchernobelskiy** [nginxinc/nginx-service-mesh#10]
I'd like to suggest merging this patch to add support for TPROXY in the listen directives:
https://trac.nginx.org/nginx/ticket/287
It's an efficient way for networking sidecars to intercept traffic and would enable a number of use cases.
Just for reference, this is one of the two supported modes in istio, and the only one that preserves IPs: https://github.com/istio/istio/blob/master/tools/packaging/common/sidecar.env#L16

**Comment by f5-todd** [comment]
@rchernobelskiy This issue is in a different repository and in turn can not be resolved with this code base.  Therefore, I am going to close the issue here, but I suggest you update [https://trac.nginx.org/nginx/ticket/287]( https://trac.nginx.org/nginx/ticket/287) with your use case.
