### ISSUE TITLE
Support Kubernetes v1.22

### ISSUE THREAD

**Issue by leecalcote** [nginxinc/nginx-service-mesh#30]
**Issue**: 

Currently, NGINX Service Mesh's charts use a deprecated version of the Mutating Webhook Configuration API.

The `admissionregistration.k8s.io/v1beta1` API version of MutatingWebhookConfiguration and ValidatingWebhookConfiguration is no longer served as of v1.22.

**Proposed Solution**:

Update use of this API to `admissionregistration.k8s.io/v1`

**Comment by sjberman** [comment]
Closing this, as we have added 1.22 support in 1.3.
