### ISSUE TITLE
Nginx service mesh M1 support

### ISSUE THREAD

**Issue by danielepolencic** [nginxinc/nginx-service-mesh#35]
It's not possible to evaluate the Nginx Service Mesh on an M1 mac.

Step to reproduce:

```bash
minikube start \
  --extra-config=apiserver.service-account-signing-key-file=/var/lib/minikube/certs/sa.key \
  --extra-config=apiserver.service-account-key-file=/var/lib/minikube/certs/sa.pub \
  --extra-config=apiserver.service-account-issuer=kubernetes/serviceaccount \
  --extra-config=apiserver.service-account-api-audiences=api
```

Deploy the nginx Service mesh

```bash
helm repo add nginx-stable https://helm.nginx.com/stable
helm repo update
helm install nsm nginx-stable/nginx-service-mesh --namespace nginx-mesh --create-namespace
```

Deploy any app

```bash
kubectl run nginx --image=nginx
```

The app is in CrashLoopBackOff. Inspecting the logs for the `service-mesh-init` init container reveals the issue:

```bash
2022/01/04 02:09:03 could not create new iptables object, reason: running [/sbin/iptables -t nat -S --wait]: exit status 3: iptables v1.8.7 (legacy): can't initialize iptables table `nat': iptables who? (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.

could not create new iptables object
gitlab.com/f5/nginx/service-mesh/product/sidecar/proxy-agent/pkg/iptables.NewIptables
	/builds/f5/nginx/service-mesh/product/sidecar/proxy-agent/pkg/iptables/iptables.go:41
main.main
	/builds/f5/nginx/service-mesh/product/sidecar/proxy-init/cmd/proxy-init/main.go:22
runtime.main
	/usr/local/go/src/runtime/proc.go:255
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1581
```

The error message led me to this other issue: https://github.com/kubernetes-sigs/kind/issues/2448

Tested on:
- M1 mac, Minikube 1.24 using the Docker driver, Docker for Desktop 4.3.2 (not working)
- Intel mac, Minikube 1.24 using the Docker driver, Docker for Desktop 4.3.2 (working)

I believe the issue is with ARM, so any ARM VM (e.g. AWS Graviton) might have the same issue.

**Comment by jbyers19** [comment]
Thanks for raising this, @danielepolencic. NGINX service mesh does not support ARM and there are no plans to add it at this time. We will update the documentation to clarify supported architectures.
