### ISSUE TITLE
How to configure Nginx Ingress Controller managed by Nginx Ingress Operator

### ISSUE THREAD

**Issue by lsorri** [nginxinc/nginx-service-mesh#39]
Hello, 

I'm trying to configure deployment (following this doc https://docs.nginx.com/nginx-service-mesh/tutorials/kic/deploy-with-kic/) of ingress controller using Ingress Operator in 
Openshift environment, I've seen that is possibile to configure the volume setup 
but I can't add any arguments in yaml manifest, is there a solution about that?

Thanks
Regards
Luigi

**Comment by kate-osborn** [comment]
Hi Luigi,

There's no way to add the service mesh related arguments to the Ingress Controller deployment that's managed by the OpenShift operator. We are working on adding support for that. It should be available in a future Ingress Controller Operator release.

**Comment by lsorri** [comment]
Hi Kate,
so at the moment you recommend to manually install the ingress controller?
Thanks
Luigi

**Comment by kate-osborn** [comment]
Yes, that's correct.

**Comment by jbyers19** [comment]
Closing as this question has been answered and there has been no further activity.
