### ISSUE TITLE
Pod to pod traffic not working - no resolver defined to resolve incoming_<svc>_<port>

### ISSUE THREAD

**Issue by leonseng** [nginxinc/nginx-service-mesh#40]
I have NSM 1.3.1 installed using Helm on AWS EKS
```
$ nginx-meshctl version
nginx-meshctl - v1.3.1
nginx-mesh-sidecar - v1.3.1
nginx-mesh-api - v1.3.1
nginx-mesh-metrics - v1.3.1
```

and have deployed a `curl` pod and `httpbin` pod within a meshed namespace. The `httpbin` pod is also exposed via a `httpbin` service on port 80.

When I tried to perform a GET request from a `curl` pod to the `httpbin` service, I get the following error
```
$ k -n httpbin-mesh exec curl-845d966998-hdplf -c curl -- curl -s httpbin/get
<html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.21.3</center>
</body>
</html>
```

The logs of the `httpbin` pod `nginx-mesh-sidecar` container shows  `no resolver defined to resolve incoming_httpbin_80` entry
```
10.0.3.62 - - [15/Mar/2022:04:56:15 +0000] "GET /get HTTP/1.1" 502 157 "-" "curl/7.82.0-DEV" "10.0.3.62" "curl-845d966998-hdplf" "spiffe://example.org/ns/httpbin-mesh/sa/default"
2022/03/15 04:56:15 [error] 1471#1471: *268 no resolver defined to resolve incoming_httpbin_80, client: 10.0.3.62, server: , request: "GET /get HTTP/1.1", host: "httpbin"
```

Any idea what caused that error?

**Comment by kate-osborn** [comment]
Hi @leonseng can you provide me with the following information:
- version of Kubernetes
- CLI command or helm values that you deployed the mesh with
- The full logs of the `nginx-mesh-sidecar` containers for the `httpbin` and `curl` Pods.

**Comment by leonseng** [comment]
I figured out what the problem is - my httpbin app is missing the following:

1. Kubernetes Service port did not have a name with `http` in it
2. Kubernetes Deployment did not have `containerPort` specified

as specified here https://docs.nginx.com/nginx-service-mesh/tutorials/deploy-example-app/

As a result, the `incoming_httpbin_80` upstream was not created in `nginx.conf` on the sidecar
