### ISSUE TITLE
Add NSM to the service mesh landscape

### ISSUE THREAD

**Issue by leecalcote** [nginxinc/nginx-service-mesh#5]
**Request:**
The [service mesh landscape](https://layer5.io/landscape) is a project/product maintainer curated index of service meshes and related technologies. This landscape is a well-referenced resource by those both in the process of adopting and those operating service meshes. We welcome NSM to be included in the service mesh landscape.

In order to ensure projects and their capabilities are accurately represented, we ask for project representatives to submit  updates to the landscape directly. Here is an open issue with contribution instructions included - https://github.com/layer5io/layer5/issues/926

_The Data Plane Matters_

**Comment by malanmurphy** [comment]
Submitted PR: https://github.com/layer5io/layer5/pull/967

**Comment by leecalcote** [comment]
Looking good! Thank you, @malanmurphy. 💪 

<img width="1163" alt="Screen Shot 2020-10-22 at 3 49 54 PM" src="https://user-images.githubusercontent.com/7570704/96928544-5043fd80-147e-11eb-9ae9-3da24a54bac1.png">

**Comment by malanmurphy** [comment]
Thanks, Lee; looks great! :)
